name: erpnew-build

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: erpnew-backend:latest

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: erpnew-frontend:latest
