// Indian states with major cities
export const INDIAN_STATES = [
  "Andhra Pradesh","Arunachal Pradesh","Assam","Bihar","Chhattisgarh",
  "Goa","Gujarat","Haryana","Himachal Pradesh","Jharkhand","Karnataka",
  "Kerala","Madhya Pradesh","Maharashtra","Manipur","Meghalaya","Mizoram",
  "Nagaland","Odisha","Punjab","Rajasthan","Sikkim","Tamil Nadu","Telangana",
  "Tripura","Uttar Pradesh","Uttarakhand","West Bengal",
  // Union Territories
  "Andaman & Nicobar Islands","Chandigarh","Dadra & Nagar Haveli and Daman & Diu",
  "Delhi","Jammu & Kashmir","Ladakh","Lakshadweep","Puducherry",
];

export const CITIES_BY_STATE = {
  "Andhra Pradesh":    ["Visakhapatnam","Vijayawada","Guntur","Nellore","Kurnool","Kadapa","Tirupati","Rajahmundry","Kakinada","Anantapur"],
  "Arunachal Pradesh": ["Itanagar","Naharlagun","Pasighat","Tawang","Ziro"],
  "Assam":             ["Guwahati","Silchar","Dibrugarh","Jorhat","Nagaon","Tinsukia","Tezpur","Bongaigaon","Dhubri","Diphu"],
  "Bihar":             ["Patna","Gaya","Bhagalpur","Muzaffarpur","Purnia","Darbhanga","Bihar Sharif","Arrah","Begusarai","Katihar"],
  "Chhattisgarh":      ["Raipur","Bhilai","Durg","Bilaspur","Korba","Rajnandgaon","Jagdalpur","Ambikapur","Chirmiri","Dhamtari"],
  "Goa":               ["Panaji","Margao","Vasco da Gama","Mapusa","Ponda","Bicholim","Calangute","Canacona"],
  "Gujarat":           ["Ahmedabad","Surat","Vadodara","Rajkot","Gandhinagar","Bhavnagar","Jamnagar","Junagadh","Anand","Navsari","Mehsana","Bharuch"],
  "Haryana":           ["Faridabad","Gurgaon","Panipat","Ambala","Yamunanagar","Rohtak","Hisar","Karnal","Sonipat","Panchkula"],
  "Himachal Pradesh":  ["Shimla","Mandi","Solan","Dharamsala","Kullu","Bilaspur","Hamirpur","Nahan","Sundernagar"],
  "Jharkhand":         ["Ranchi","Jamshedpur","Dhanbad","Bokaro","Deoghar","Phusro","Hazaribag","Giridih","Ramgarh","Medininagar"],
  "Karnataka":         ["Bengaluru","Mysuru","Hubli","Mangaluru","Belagavi","Kalaburagi","Ballari","Vijayapura","Shivamogga","Tumkur","Davangere","Hassan"],
  "Kerala":            ["Thiruvananthapuram","Kochi","Kozhikode","Kollam","Thrissur","Palakkad","Alappuzha","Kannur","Kasaragod","Kottayam"],
  "Madhya Pradesh":    ["Indore","Bhopal","Jabalpur","Gwalior","Ujjain","Sagar","Dewas","Satna","Ratlam","Rewa","Murwara","Singrauli"],
  "Maharashtra":       ["Mumbai","Pune","Nagpur","Nashik","Aurangabad","Solapur","Amravati","Nanded","Kolhapur","Sangli","Thane","Vasai-Virar","Kalyan"],
  "Manipur":           ["Imphal","Thoubal","Bishnupur","Churachandpur","Ukhrul"],
  "Meghalaya":         ["Shillong","Tura","Nongstoin","Jowai","Baghmara"],
  "Mizoram":           ["Aizawl","Lunglei","Saiha","Champhai","Kolasib"],
  "Nagaland":          ["Kohima","Dimapur","Mokokchung","Tuensang","Wokha"],
  "Odisha":            ["Bhubaneswar","Cuttack","Rourkela","Berhampur","Sambalpur","Puri","Balasore","Bhadrak","Baripada","Jharsuguda"],
  "Punjab":            ["Ludhiana","Amritsar","Jalandhar","Patiala","Bathinda","Mohali","Firozpur","Hoshiarpur","Gurdaspur","Moga"],
  "Rajasthan":         ["Jaipur","Jodhpur","Kota","Bikaner","Ajmer","Udaipur","Bhilwara","Alwar","Bharatpur","Sikar","Pali","Sri Ganganagar"],
  "Sikkim":            ["Gangtok","Namchi","Mangan","Gyalshing"],
  "Tamil Nadu":        ["Chennai","Coimbatore","Madurai","Tiruchirappalli","Salem","Tirunelveli","Tiruppur","Erode","Vellore","Thoothukudi","Dindigul","Thanjavur"],
  "Telangana":         ["Hyderabad","Warangal","Nizamabad","Karimnagar","Khammam","Mahbubnagar","Ramagundam","Nalgonda","Adilabad","Suryapet"],
  "Tripura":           ["Agartala","Udaipur","Dharmanagar","Kailasahar","Belonia"],
  "Uttar Pradesh":     [
    "Lucknow","Kanpur","Agra","Varanasi","Prayagraj","Meerut","Ghaziabad","Noida",
    "Bareilly","Aligarh","Moradabad","Gorakhpur","Mathura","Firozabad","Saharanpur",
    "Muzaffarnagar","Shahjahanpur","Rampur","Jhansi","Hapur","Sambhal","Ayodhya",
    "Mirzapur","Bulandshahr","Lakhimpur Kheri","Sitapur","Hardoi","Unnao","Rae Bareli",
    "Fatehpur","Pratapgarh","Jaunpur","Gonda","Bahraich","Sultanpur","Azamgarh",
    "Deoria","Basti","Ballia","Etawah","Mainpuri","Banda","Chitrakoot","Hamirpur",
    "Mahoba","Lalitpur","Kasganj","Hathras","Amroha","Bijnor","Shamli","Badaun",
    "Pilibhit","Kushinagar","Maharajganj","Siddharthnagar","Sant Kabir Nagar",
    "Ambedkar Nagar","Amethi","Barabanki","Farrukhabad","Kannauj","Auraiya",
    "Etah","Vrindavan","Orai","Ghazipur","Mau","Sonbhadra","Chandauli",
    "Greater Noida","Brij","Sahibabad","Loni","Firozabad","Shikohabad",
  ],
  "Uttarakhand":       ["Dehradun","Haridwar","Roorkee","Haldwani","Rudrapur","Rishikesh","Kashipur","Sitarganj","Pithoragarh","Nainital"],
  "West Bengal":       ["Kolkata","Asansol","Siliguri","Durgapur","Bardhaman","Malda","Baharampur","Habra","Kharagpur","Shantipur","Darjeeling","Jalpaiguri"],
  "Andaman & Nicobar Islands": ["Port Blair","Ferrargunj","Rangat","Diglipur"],
  "Chandigarh":        ["Chandigarh"],
  "Dadra & Nagar Haveli and Daman & Diu": ["Silvassa","Daman","Diu"],
  "Delhi":             ["New Delhi","Delhi","Dwarka","Rohini","Janakpuri","Laxmi Nagar","Pitampura","Saket","Karol Bagh","Connaught Place"],
  "Jammu & Kashmir":   ["Srinagar","Jammu","Anantnag","Baramulla","Sopore","Udhampur","Kathua","Pulwama"],
  "Ladakh":            ["Leh","Kargil"],
  "Lakshadweep":       ["Kavaratti","Agatti","Minicoy"],
  "Puducherry":        ["Puducherry","Karaikal","Mahe","Yanam"],
};
